import sys
import numpy as np
from numpy import random as rnd
from matplotlib import pyplot as plt


def train(n):
    """
    A function that trains a model to predict house prices based on provided train data (heart_train.csv).

    :param n: polynomial order, where 1 means linear, 2 means 2nd order, 3 means 3rd order.
    """
    # ----------------- default output files ----------------- #
    output_file = "Linear_Train_Results.txt"
    output_thetas = "linear_thetas"
    # ---------------------- Read input ---------------------- #
    x = np.transpose(np.loadtxt("heart_train.csv", delimiter=',', skiprows=1, usecols=range(13)))
    y = np.loadtxt("heart_train.csv", delimiter=',', skiprows=1, usecols=-1)
    # ------------------- Feature Scaling -------------------- #
    s_factor = np.amax(x, axis=1)
    x = x / s_factor[:, None]

    num_of_examples = x.shape[1]
    # --------- Manipulate input data for processing --------- #
    """
        trainX = [1 , 1,  1  ... ] <--- To be multiplied by Theta0
                 [x1, x2, x3 ... ] <--- Feature 1, multiplies by Theta1
                 [v1, v2, v3 ... ] <--- Feature 2, multiplied by Theta2
                 ... etc

        trainY = [Y1, Y2, Y3 ... ]
    """
    trainY = y
    trainX = np.vstack([np.ones(num_of_examples), x])

    # Based on input, choose whether to go with linear model (power 1), power2, or power3.
    if n == 1:  # linear (power 1)
        pass
    elif n == 2:  # power 2
        trainX = np.vstack([trainX, np.square(x)])
        output_file = "Polynomial_order2_Train_Results.txt"
        output_thetas = "Polynomial_order2_thetas"
    elif n == 3:  # power 3
        trainX = np.vstack([trainX, np.square(x), np.power(x, 3)])
        output_file = "Polynomial_order3_Train_Results.txt"
        output_thetas = "Polynomial_order3_thetas"
    num_of_features = trainX.shape[0]

    # ------------ Thetas random start point ------------ #
    thetas = rnd.random(num_of_features)
    # ----------------- Learning rate ------------------- #
    lr = 0.001
    # ----------------- Initialize loss ----------------- #
    loss = list()
    hyp = None
    # -------------------- Main Loop -------------------- #
    for i in range(300000):
        """ hypothesis hyp = [h1 , h2,  h3  ... ]. (This is the guess generated by current value of theta)"""
        hyp = 1 / (1 + np.exp(-np.dot(thetas, trainX)))

        """ Update theta"""
        # The vstack below works only for single row vectors. so if hyp was [[2,3,3],[1,1,1]] then it wont work
        grad = np.dot(trainX, np.vstack(hyp - trainY) / num_of_examples)
        thetas = thetas - (lr * np.hstack(grad))

        """Calculate loss"""
        loss.append(-np.sum(np.log(hyp) * trainY + np.log(1 - hyp) * (1 - trainY)) / num_of_examples)
        relative_loss = abs((loss[i] - loss[i - 1]) / loss[i] * 100)
        if relative_loss <= 0.0001 and i != 0:
            print("Stopped at iteration: " + str(i))
            break

    # --------------------- output area ---------------------- #
    # Console output
    print("loss is: " + str(loss[-1]))
    correct = 0
    for i in range(len(hyp)):
        if hyp[i] > 0.5:
            print("The predicted class is: ", 1, ", the actual class is: ", y[i], ",   ", y[i] == 1)
            if y[i] == 1:
                correct = correct + 1
        else:
            print("The predicted class is: ", 0, ", the actual class is: ", y[i], ",   ", y[i] == 0)
            if y[i] == 0:
                correct = correct + 1
    print("Number of correct guesses is: ", correct)

    # File output
    np.save(output_thetas, thetas)  # Save thetas for the test phase.

    # Plot of loss
    plt.plot(loss)
    plt.show()


def test():
    """
    A function that tests the trained model, based on provided test data set (heart_test.csv)
    :return:
    """
    # ----------------- Reading Input ---------------- #
    x = np.transpose(np.loadtxt("heart_train.csv", delimiter=',', skiprows=1, usecols=range(13)))
    y = np.loadtxt("heart_train.csv", delimiter=',', skiprows=1, usecols=-1)
    # ------------------- Feature Scaling -------------------- #
    s_factor = np.amax(x, axis=1)
    x = x / s_factor[:, None]
    (x_m, x_n) = x.shape

    print("\n\n#==================== X and Y ====================#")
    print(x)
    print(y)

    # ---------------------- Linear Test ---------------------- #
    print("\n\n#==================== Linear Testing ====================#")
    train_thetas = np.load("linear_thetas.npy")

    testX = np.vstack([np.ones(x_n), x])
    testY = y
    hyp = 1 / (1 + np.exp(-np.dot(train_thetas, testX)))
    print("Hypothesis Overview:")
    print(hyp)
    test_loss = -np.sum(np.log(hyp) * testY + np.log(1 - hyp) * (1 - testY)) / x_n
    print("Linear Test Loss is: " + str(test_loss))
    # ------------------- Test Linear Done ------------------- #

    # TODO: Edit the following block (from linear regression in a previous projtect) so it is compatible with current
    #  one

    # # Show which model was the best
    # best_loss = min(zip(losses.values(), losses.keys()))[1]
    # print("\n----------------------------------------------------------------------------------------"
    #       "\nThe best model in terms of loss is: {model} model, "
    #       "with loss equal to {loss}"
    #       "\n----------------------------------------------------------------------------------------"
    #       "\n\n".format(model=best_loss, loss=losses[best_loss]))

# TODO: Implement terminal commands to run the program.
if __name__ == "__main__":
    train(1)

    # if len(sys.argv) == 1:
    #     print("not enough arguments.\n"
    #           "Use the following arguments in command line:\n"
    #           "\tT1: Train a linear model\n"
    #           "\tT2: Train a polynomial model of order 2\n"
    #           "\tT3: Train a polynomial model of order 3\n"
    #           "\tV: validate(test) the trained models")
    #     exit()
    #
    # if sys.argv[1].upper() == "T1":
    #     train(1)
    # elif sys.argv[1].upper() == "T2":
    #     train(2)
    # elif sys.argv[1].upper() == "T3":
    #     train(3)
    # elif sys.argv[1].upper() == "V":
    #     test()
    # else:
    #     print("wrong command line argument.")
    #     exit()
